default_context:
  project_name: 'markdown-html'
  project_slug: 'markdown-html'
  domain_main: 'mark.joshcisar.com'
  domain_staging: 'stag.mark.joshcisar.com'
  docker_swarm_stack_name_main: 'mark-joshcisar-com'
  docker_swarm_stack_name_staging: 'stag-mark-joshcisar-com'
  secret_key: '58a3e9979cfc1a053b58e17c353f7c4b894d29ddb465a994b7cd2f1802313047'
  first_superuser: 'joshcisar@gmail.com'
  first_superuser_password: 'jeffsson2'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mark.joshcisar.com", "https://stag.mark.joshcisar.com", "https://mark.joshcisar.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mark.joshcisar.com'
  postgres_password: 'jeffsson2'
  pgadmin_default_user: 'joshcisar@gmail.com'
  pgadmin_default_user_password: 'jeffsson2'
  traefik_constraint_tag: 'mark.joshcisar.com'
  traefik_constraint_tag_staging: 'stag.mark.joshcisar.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:jeffsson2'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
